name: abyssal4
channels:
    - pytorch
    - conda-forge
    - bioconda
dependencies:
    - python==3.9.9
    - pandas==1.3.5
    - matplotlib
    - seaborn
#    - pytorch==1.10.1
    - scikit-learn
    - cython
    - omegaconf
    - pip<=24.1
    - numpy
    - pip:
      - pytorch-lightning==1.5.9
      - torch==1.10.1
      - hydra-core
      - fair-esm
#      - numpy>=1.23
