name: abyssal 
channels:
    - pytorch
    - conda-forge
    - bioconda
dependencies:
    - python==3.9.9
    - pandas==1.3.5
    - matplotlib
    - seaborn
    - pytorch==1.10.1
    - scikit-learn
    - cython
    - omegaconf
    - pip
    - pip:
      - pytorch-lightning==1.5.9
      - hydra-core
      - fair-esm
      - numpy==1.21.2 
