batch_size: 512
layer: 33
esm_model: esm2_t33_650M_UR50D
mode: predict


input: null
output: null
model_path: null

# input: /trinity/home/s.mishra/mega_ddg/data/embeddings/myoglobin_embeddings.npy
# output: predictions.tsv
# model_path: random_split.pt

model:
  embeddings_dim: 1280
  conv_dropout: 0.1
  kernel_size: 9
  attention: False
  
train:
  max_epochs: 100