batch_size: 512
layer: 33
esm_model: esm2_t33_650M_UR50D
mode: predict


input: null
output: null
model_path: models/ddg_model_trained_on_mega.pt 

model:
  embeddings_dim: 1280
  conv_dropout: 0.1
  kernel_size: 9
  attention: False
  
train:
  max_epochs: 100

hydra:
  output_subdir: null
  run:  
    dir: .